#Nome e apelidos
version: "3"
services:
  web:
    build: apache
    ports:
      - 80:80
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./documentos:/app/alberto/
      - ./apache/ports.conf:/etc/apache2/ports.conf
      - ./apache/error.log:/var/log/apache2/alberto.acasadepapel.lan/
    networks:
      my_network:
        ipv4_address: 192.168.121.40    
  cliente-firefox:
    image: kasmweb/firefox:1.14.0
    ports:
     - 6901:6901
    environment:
      - VNC_PW=abc123.  #Usuario kasm_user
    extra_hosts:
      - "alberto.acasadepapel.lan:192.168.121.40"
      - "www.alberto.acasadepapel.lan:192.168.121.40"
    networks:
      my_network:
        ipv4_address: 192.168.121.51
  cliente:
    build: cliente
    extra_hosts:
      - "alberto.acasadepapel.lan:192.168.121.40"
      - "www.alberto.acasadepapel.lan:192.168.121.40"
    networks:
      my_network:  
        ipv4_address: 192.168.121.52  
  cliente2:
    build: cliente
    extra_hosts:
      - "alberto.acasadepapel.lan:192.168.121.40"
      - "www.alberto.acasadepapel.lan:192.168.121.40"
    networks:
      my_network:    
        ipv4_address: 192.168.121.180

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.121.0/24